// <auto-generated />
namespace GESTIONSCOLAIRE_EXAMEN.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class examenmigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(examenmigration));
        
        string IMigrationMetadata.Id
        {
            get { return "202503070344162_examen-migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
